baseURL                          = "https://dave-reid-memorial.netlify.app/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showMenu                     = true                    # Show navigation menu
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "2006-01-02"
    email                        = "megan.reid85+dave@gmail.com"
    customCSS                    = ["site.css"]            # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        localTime                = false                   # Show your current local time in contact section
        timeZone                 = "Europe/London"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-GB"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # To enable giscus, the GitHub-discussions-based comment section,
    # input the repository for the discussions below. For more details, see
    # https://www.joelnitta.com/posts/2021-11-24_using-giscus/
    # and https://github.com/giscus/giscus
    [params.giscus]
        # repo = "github-user/github-repo" # Entering repo will enable giscus
        repo-id = "enter-repo-id"
        category = "Comments"
        category-id = "enter-category-id"
        mapping = "pathname"
        reactions-enabled = "1"
        emit-metadata = "0"
        theme = "light"
        lang = "en"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-gb"
        contentDir       = "content/en"
        weight           = 0
        title            = "David Reid"
        [languages.en.params]
            description  = "David Reid date-date"
            footerText   = ""
