backend:
  name: git-gateway
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "content"
    label: "content"
    folder: "site/content"
    create: false
    fields:
      - {label: "Title", name: "title", widge: "string"}
      - {label: "Body", name: "body", widget: "markdown"}